apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # 앞서 생성한 발급자 지정
    cert-manager.io/cluster-issuer: http-issuer
  name: nginx-tls

spec:
  rules:
    - host: k8s.realizeme.o-r.kr
      http:
        paths:
          - path: /
            backend:
              serviceName: subway-service
              servicePort: 80

  tls:
    - hosts:
        - [외부에서 접근할 도메인]

      # Secret 리소스를 생성하지 않아도 cert-manager에서 자동으로 인증서를 발급받아서 Secret을 생성한다. 사용자는 생성될 Secret의 이름만 지정하면 된다.
      secretName: nginx-tls